emartech/emarsys-integration-js

README.md
client/app/message_handler/navigate.js
client/app/message_handler/navigate.spec.js

Provide test for campaign copy endpoint

feat(navigate): add endpoint for copy campaign

---

.eslintrc
README.md
client/app/message_handler/navigate.js
client/app/message_handler/navigate.spec.js

Add administrator list navigation

---

README.md
client/app/message_handler/navigate.js
client/app/message_handler/navigate.spec.js

Add endpoint to create new campaign with parameters

feat(navigate): add endpoint for create campaign

---

client/app/message_handler/intercom_track_event.js
client/app/message_handler/intercom_track_event.spec.js

Review, please! :) Thanks in advance.

fix(intercom): fix calling Intercom

---

client/app/message_handler/navigate.js
client/app/message_handler/navigate.spec.js

feat(navigate): add endpoint contact/edit page

---

client/app/service/dialog_api.js
package-lock.json
package.json

chore(package): update to jquery 3

---

client/app/message_handler/navigate.spec.js
client/app/message_handler/url_targets.js

fix(tactics/details): fix tactic details link

---

client/app/message_handler/navigate.spec.js
client/app/message_handler/url_targets.js

fix(tactics/details): fix tactic details link
REPORTING-0185

fix tactics list link, #2 (#39)

---

client/app/message_handler/navigate.spec.js
client/app/message_handler/url_targets.js

Co-Authored-By: tmolnar <tamas.molnar@emarsys.com>

feat(navigate): adds program summary navigation endpoints

---

README.md
client/app/message_handler/navigate.spec.js
client/app/message_handler/url_targets.js

SUITEDEV-19378
Co-authored-by: rudywaltz <david.barkoczi@gmail.com>
Co-authored-by: Justin Walker <justin.walker@emarsys.com>

feat(navigate): add campaign list for push and inapp

---

README.md
client/app/message_handler/navigate.spec.js
client/app/message_handler/url_targets.js

This PR introduce new target in navigation for RTI program report page

feat(navigate): add rti program report as target url AA-2387

---

README.md
client/app/message_handler/navigate.spec.js
client/app/message_handler/url_targets.js

SUITEDEV-22321
Co-authored-by: vspasevski@emarsys.com <vspasevski@emarsys.com>
Co-authored-by: boristomic <boris.tomic@emarsys.com>

feat(push): add urls for push and inapp campaign reports SUITEDEV-22321

---

README.md
client/app/message_handler/url_targets.js

feat(navigation): add revenue attribution settings

---

README.md
client/app/message_handler/url_targets.js

EME-259
Co-authored-by: Adam Fentosi <fentosi.adam@gmail.com>

feat(navigate): add homepage

---

client/app/message_handler/navigate.spec.js
client/app/message_handler/url_targets.js

SUITEDEV-23844
Co-authored-by:  Boris Tomic <boris.tomic@emarsys.com

feat(navigate): add inbox endpoint

---

client/app/message_handler/navigate.spec.js
client/app/message_handler/url_targets.js

AA-6592
Co-authored-by: gergaczd <gergaczdaniel@gmail.com>

fix(navigate): fix rti/report target

---

README.md
client/app/message_handler/navigate.spec.js
client/app/message_handler/url_targets.js

Adds edit form url to use this with rti node dialog's edit resource button

Production

---

README.md
client/app/message_handler/navigate.spec.js
client/app/message_handler/url_targets.js

the old target shall be rewritten
SUITEDEV-26144

feat(navigate): remove target for AC program edit in unified editor

---

README.md

chore(readme): clarify id parameter

---

README.md
client/app/message_handler/navigate.spec.js
client/app/message_handler/url_targets.js

AA-7867
Co-authored-by: Benjamin Dorogi <bdorogi@emarsys.com>

feat(navigate): add sms/dashboard target for sms dashboard

---

client/app/message_handler/url_targets.js

feat: add web-push targets

---

README.md
client/app/message_handler/url_targets.js

Co-authored-by: szabolcsadam <szabolcs.adam@emarsys.com>

feat(navigate): add combined segment create SEG-12

---

README.md
client/app/message_handler/url_targets.js

Co-authored-by: Gabor Pap <gabor.pap@emarsys.com>
Co-authored-by: Krisztian Kimak <krisztian.kimak@emarsys.com>

feat(navigate): add combined segment edit SEG-14
